### ISSUE TITLE
"I am still going" missing in exercise 20 sliceref

### ISSUE THREAD

**Issue by SRNissen** [soypat/gopherlings#10]
#### Background
I finished exercise 19 and the gopherlings watch window gave me an error message that did not at all resemble exercise 20 (because it skipped directly to exercise 21)

#### Proposed change

Add

    // I AM STILL GOING

to exercise 20

EDIT: Also separately - **thank you for maintaining this repo.** Despite what my issues might indicate, I am very happy to have this training resource.

**Comment by soypat** [comment]
You are correct- and the comment is also missing in excercises 31 and 32, which is the root cause of #11. Let me know if you want to create a PR for them!

**Comment by SRNissen** [comment]
I do, thank you. It'll show up at some point later today when I can fit it in.

**Comment by soypat** [comment]
Feel free to file a PR for #9 as well, no rush!
