### ISSUE TITLE
Use "air" cli to make excise running automatically

### ISSUE THREAD

**Issue by benluo** [soypat/gopherlings#3]
I always use [air](https://github.com/cosmtrek/air) when I develop go program. It will run main.go automatically when I change the code.

If I use `air` instead of `go run main.go`. I can just focus on correcting code.

**Comment by soypat** [comment]
Looks cool! Maybe this could be added as a suggestion in the README just under `Instructions: Running exercises`. Would you mind submitting a PR?

**Comment by soypat** [comment]
Resolved with #4.
