### ISSUE TITLE
Suggested correction to explanatory text for exercise 14

### ISSUE THREAD

**Issue by SRNissen** [soypat/gopherlings#9]
The current text is technically false. As of today, it is written:

    // Problem:
    // For statements can also have init and post statements in the clause.
    //
    //  for i := 0; i <= 10; i = i + 1 {
    //      fmt.Println(i)
    //  }
    //
    // The above for loop will iterate from 0 to 10 and is
    // identical in functionality to the following
    // single-condition for statement:
    //
    //  i := 0
    //  for i <= 10 {
    //      fmt.Println(i)
    //      i = i + 1
    //  }

which would leave `i` in scope after the loop block, which is true in some languages but not here.

#### Proposed change

The exercise text could instead be

    // Problem:
    // For statements can also have init and post statements in the clause.
    //
    //  for i := 0; i <= 10; i = i + 1 {
    //      fmt.Println(i)
    //  }
    //
    // The above for loop will iterate from 0 to 10 and is
    // identical in functionality to the following
    // single-condition for statement:
    //
    // {
    //      i := 0
    //      for i <= 10 {
    //          fmt.Println(i)
    //          i = i + 1
    // }

**Comment by soypat** [comment]
I'm a bit on the fence with the idea of adding anonymous scopes as that is a feature that may catch some off guard. Maybe we can change the comment:
```c
// The above for loop will iterate from 0 to 10.
// The following single-condition for statement
// will also perform the same operations:
```

This sound good?

**Comment by SRNissen** [comment]
It does
